In [1]:
from dataset_io import *

In [2]:
contacts, contactlesses = read_dataset(DATASET_NAME)

In [14]:
print(type(contactlesses[0]))
print(contactlesses)
print(type(contactlesses[0][0]))
print(contactlesses.shape)
print(contacts.shape)

<class 'numpy.ndarray'>
[[520. 521. 523. ... 521. 520. 523.]
 [565. 656. 613. ... 518. 525. 549.]
 [517. 521. 529. ... 521. 521. 522.]
 ...
 [523. 517. 525. ... 524. 523. 523.]
 [525. 521. 517. ... 519. 521. 525.]
 [524. 518. 521. ... 523. 523. 524.]]
<class 'numpy.float64'>
(161, 1022)
(161, 1022)


In [ ]:
def get_training_set(contacts, contactlesses, sample_length):
    dataset_length, 